title: "alshin"
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
plugins_dir: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
github_username: yunshang
paginate: 10
paginate_path: "page:num"
baseurl: ""
#baseurl: /blog/
